import { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import ClinicReportView from "@/components/reports/ClinicReportView";
import { AlertCircle } from "lucide-react";

export default function SharedReportView() {
  const { token } = useParams();
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      try {
        const res = await base44.functions.invoke("getSharedReport", { token });
        if (res.data?.error) {
          setError(res.data.error);
        } else {
          setData(res.data);
        }
      } catch (e) {
        setError(e.message || "Failed to load report");
      }
      setLoading(false);
    })();
  }, [token]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-secondary border-t-primary rounded-full animate-spin" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center p-6">
        <div className="text-center max-w-sm">
          <AlertCircle size={32} className="text-muted-foreground mx-auto mb-3" />
          <h1 className="font-heading text-xl font-bold mb-1">{error}</h1>
          <p className="text-sm text-muted-foreground">This link may have expired or is no longer valid. Please ask the patient to generate a new one.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="border-b bg-card/50 px-6 py-3 print:hidden">
        <p className="text-xs text-muted-foreground text-center">Read-only clinic report · Generated by PD Companion</p>
      </div>
      <ClinicReportView data={data} />
    </div>
  );
}